name: Integration Test

on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:

jobs:
  integration:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - uses: asdf-vm/actions/install@v2
      - uses: bluefireteam/melos-action@v3
      - run: sudo apt update
      - run: sudo apt install -y clang cmake libblkid-dev libglib2.0-dev libgtk-3-dev liblzma-dev network-manager ninja-build packagekit pkg-config polkitd xvfb
      - run: |
          cd packages/app_center && \
          sudo cp integration_test/assets/snapd-ci.pkla /var/lib/polkit-1/localauthority/50-local.d/
          LANG=en_US.UTF-8 xvfb-run -a -s '-screen 0 1024x768x24 +extension GLX' \
          flutter test integration_test
